export const apiConfig = {
  baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://132.154.156.82:5999',
  timeout: 15000,
  endpoints: {
    auth: {
      login: '/api/auth/login',
      logout: '/api/auth/logout',
      me: '/api/auth/me',
    },
    users: {
      list: '/api/users/',
      create: '/api/users/',
      get: (id: number) => `/api/users/${id}`,
      update: (id: number) => `/api/users/${id}`,
      deactivate: (id: number) => `/api/users/${id}`,
    },
    admin: {
      config: '/api/admin/config',
      tokenConfig: '/api/admin/token-config',
      tokenConfigReset: '/api/admin/token-config/reset',
    },
    payment: {
      initiate: '/api/payment/initiate',
      receipt: (id: number) => `/api/payment/receipt/${id}`,
      byReceiptNo: (receiptNo: string) => `/api/payment/by-receipt/${receiptNo}`,
    },
    collector: {
      summary: '/api/collector/summary',
      payments: '/api/collector/payments',
      events: '/api/collector/events',
    },
    dashboard: {
      summary: '/api/dashboard/summary',
      collectors: '/api/dashboard/collectors',
      payments: '/api/dashboard/payments',
      events: '/api/dashboard/events',
    },
    pledge: {
      list: '/api/pledge/',
      create: '/api/pledge/',
      get: (id: number) => `/api/pledge/${id}`,
      pay: (id: number) => `/api/pledge/${id}/pay`,
      cancel: (id: number) => `/api/pledge/${id}/cancel`,
    },
    donor: {
      list: '/api/donor/',
      get: (id: number) => `/api/donor/${id}`,
    },
    events: {
      list:    '/api/events/',
      active:  '/api/events/active',
      create:  '/api/events/',
      get:     (id: number) => `/api/events/${id}`,
      update:  (id: number) => `/api/events/${id}`,
      days:    (id: number) => `/api/events/${id}/days`,
      cover:   (id: number) => `/api/events/${id}/cover`,
      gallery: (id: number) => `/api/events/${id}/gallery`,
      summary: (id: number) => `/api/events/${id}/summary`,
    },
    media: {
      delete: (id: number) => `/api/media/${id}`,
    },
    public: {
      siteConfig:    '/api/public/site-config',
      events:        '/api/public/events',
      eventBySlug:   (slug: string) => `/api/public/events/${slug}`,
      featuredEvent: '/api/public/featured-event',
      announcements: '/api/public/announcements',
      committee:     '/api/public/committee',
    },
    contact: {
      submit:       '/api/contact/submit',
      queries:      '/api/contact/queries',
      queryDetail:  (id: number) => `/api/contact/queries/${id}`,
      queryStatus:  (id: number) => `/api/contact/queries/${id}/status`,
    },
    announcements: {
      list:   '/api/announcements/',
      create: '/api/announcements/',
      get:    (id: number) => `/api/announcements/${id}`,
      update: (id: number) => `/api/announcements/${id}`,
      delete: (id: number) => `/api/announcements/${id}`,
    },
    committee: {
      list:   '/api/committee/',
      create: '/api/committee/',
      get:    (id: number) => `/api/committee/${id}`,
      update: (id: number) => `/api/committee/${id}`,
      delete: (id: number) => `/api/committee/${id}`,
      photo:  (id: number) => `/api/committee/${id}/photo`,
    },
    token: {
      generate: '/api/token/generate',
      bulk: '/api/token/bulk',
      list: '/api/token/list',
      get: (tokenNo: string) => `/api/token/${tokenNo}`,
      void: (tokenNo: string) => `/api/token/${tokenNo}/void`,
    },
  },
  backendPages: {
    payQr: (paymentId: number) => `/pay/qr/${paymentId}`,
    payCash: (paymentId: number) => `/pay/cash/${paymentId}`,
    payCheque: (paymentId: number) => `/pay/cheque/${paymentId}`,
    payReceipt: (paymentId: number) => `/pay/receipt/${paymentId}`,
    receipt: (receiptNo: string) => `/receipt/${receiptNo}`,
    tokenView: (tokenNo: string) => `/token/${tokenNo}`,
    tokenPrint: (tokenNo: string) => `/token/print/${tokenNo}`,
    tokenPrintBulk: (batchId: string) => `/token/print/bulk/${batchId}`,
  },
} as const
