export const apiConfig = {
  baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://132.154.156.82:5999',
  timeout: 15000,
  endpoints: {
    auth: {
      login: '/api/auth/login',
      logout: '/api/auth/logout',
      me: '/api/auth/me',
      firstSetup: '/api/auth/first-setup',
    },
    users: {
      list: '/api/users/',
      create: '/api/users/',
      get: (id: number) => `/api/users/${id}`,
      update: (id: number) => `/api/users/${id}`,
      deactivate: (id: number) => `/api/users/${id}`,
      loginQr: (id: number) => `/api/users/${id}/login-qr`,
    },
    admin: {
      config: '/api/admin/config',
      tokenConfig: '/api/admin/token-config',
      tokenConfigReset: '/api/admin/token-config/reset',
    },
    payment: {
      initiate: '/api/payment/initiate',
      receipt: (id: number) => `/api/payment/receipt/${id}`,
      byReceiptNo: (receiptNo: string) => `/api/payment/by-receipt/${receiptNo}`,
    },
    collector: {
      summary: '/api/collector/summary',
      payments: '/api/collector/payments',
      events: '/api/collector/events',
    },
    dashboard: {
      summary: '/api/dashboard/summary',
      collectors: '/api/dashboard/collectors',
      payments: '/api/dashboard/payments',
      events: '/api/dashboard/events',
      eventReport: (id: number) => `/api/dashboard/event-report/${id}`,
    },
    pledge: {
      list: '/api/pledge/',
      create: '/api/pledge/',
      get: (id: number) => `/api/pledge/${id}`,
      pay: (id: number) => `/api/pledge/${id}/pay`,
      cancel: (id: number) => `/api/pledge/${id}/cancel`,
    },
    donor: {
      list: '/api/donor/',
      get: (id: number) => `/api/donor/${id}`,
    },
    events: {
      list:          '/api/events/',
      active:        '/api/events/active',
      create:        '/api/events/',
      get:           (id: number) => `/api/events/${id}`,
      update:        (id: number) => `/api/events/${id}`,
      days:          (id: number) => `/api/events/${id}/days`,
      cover:         (id: number) => `/api/events/${id}/cover`,
      gallery:       (id: number) => `/api/events/${id}/gallery`,
      galleryReorder:(id: number) => `/api/events/${id}/gallery/reorder`,
      summary:       (id: number) => `/api/events/${id}/summary`,
    },
    expenses: {
      list:   '/api/expenses/',
      detail: (id: number) => `/api/expenses/${id}`,
    },
    contributions: {
      submit:        '/api/contributions/',
      myList:        '/api/contributions/me',
      myStats:       '/api/contributions/me/stats',
      paymentInfo:   '/api/contributions/payment-info',
      screenshot:    (id: number) => `/api/contributions/screenshot/${id}`,
      adminList:     '/api/contributions/admin',
      adminStats:    '/api/contributions/admin/stats',
      adminReview:   (id: number) => `/api/contributions/admin/${id}/review`,
    },
    budgets: {
      list:       '/api/budgets/',
      report:     '/api/budgets/report',
      allSummary: '/api/budgets/all-summary',
      detail:     (id: number) => `/api/budgets/${id}`,
      reorder:    '/api/budgets/reorder',
    },
    media: {
      delete: (id: number) => `/api/media/${id}`,
    },
    public: {
      siteConfig:    '/api/public/site-config',
      events:        '/api/public/events',
      eventBySlug:   (slug: string) => `/api/public/events/${slug}`,
      featuredEvent: '/api/public/featured-event',
      gallery:       '/api/public/gallery',
      stats:         '/api/public/stats',
      announcements: '/api/public/announcements',
      committee:     '/api/public/committee',
      platformUpi:   '/api/public/platform-upi',
      platformUpiQr: '/api/public/platform-upi-qr',
      orgRequest:    '/api/public/org-request',
    },
    contact: {
      submit:       '/api/contact/submit',
      queries:      '/api/contact/queries',
      queryDetail:  (id: number) => `/api/contact/queries/${id}`,
      queryStatus:  (id: number) => `/api/contact/queries/${id}/status`,
    },
    announcements: {
      list:   '/api/announcements/',
      create: '/api/announcements/',
      get:    (id: number) => `/api/announcements/${id}`,
      update: (id: number) => `/api/announcements/${id}`,
      delete: (id: number) => `/api/announcements/${id}`,
    },
    circulars: {
      // Admin
      list:   '/api/circulars/',
      create: '/api/circulars/',
      get:    (id: number) => `/api/circulars/${id}`,
      update: (id: number) => `/api/circulars/${id}`,
      delete: (id: number) => `/api/circulars/${id}`,
      // Member
      published:       '/api/circulars/published',
      publishedDetail: (id: number) => `/api/circulars/published/${id}`,
    },
    committee: {
      list:    '/api/committee/',
      create:  '/api/committee/',
      get:     (id: number) => `/api/committee/${id}`,
      update:  (id: number) => `/api/committee/${id}`,
      delete:  (id: number) => `/api/committee/${id}`,
      photo:   (id: number) => `/api/committee/${id}/photo`,
      reorder: '/api/committee/reorder',
    },
    token: {
      generate: '/api/token/generate',
      bulk: '/api/token/bulk',
      list: '/api/token/list',
      get: (tokenNo: string) => `/api/token/${tokenNo}`,
      void: (tokenNo: string) => `/api/token/${tokenNo}/void`,
    },
    org: {
      register: '/api/org/register',
      me:       '/api/org/me',
    },
    meetings: {
      // Admin
      list:            '/api/meetings/',
      create:          '/api/meetings/',
      get:             (id: number) => `/api/meetings/${id}`,
      update:          (id: number) => `/api/meetings/${id}`,
      delete:          (id: number) => `/api/meetings/${id}`,
      invitees:        (id: number) => `/api/meetings/${id}/invitees`,
      removeInvitee:   (id: number, uid: number) => `/api/meetings/${id}/invitees/${uid}`,
      adminAttendance: (id: number) => `/api/meetings/${id}/attendance`,
      agenda:          (id: number) => `/api/meetings/${id}/agenda`,
      agendaItem:      (itemId: number) => `/api/meetings/agenda/${itemId}`,
      discussions:     (id: number) => `/api/meetings/${id}/discussions`,
      discussion:      (discId: number) => `/api/meetings/discussions/${discId}`,
      // Member
      myList:              '/api/meetings/me',
      myDetail:            (id: number) => `/api/meetings/me/${id}`,
      myAgenda:            (id: number) => `/api/meetings/me/${id}/agenda`,
      myDiscussions:       (id: number) => `/api/meetings/me/${id}/discussions`,
      myAttendanceStatus:  (id: number) => `/api/meetings/me/${id}/attendance/status`,
      myMarkAttendance:    (id: number) => `/api/meetings/me/${id}/attendance`,
    },
    actionPlans: {
      // Admin
      list:           '/api/action-plans/',
      create:         '/api/action-plans/',
      get:            (id: number) => `/api/action-plans/${id}`,
      update:         (id: number) => `/api/action-plans/${id}`,
      delete:         (id: number) => `/api/action-plans/${id}`,
      assignees:      (id: number) => `/api/action-plans/${id}/assignees`,
      removeAssignee: (id: number, uid: number) => `/api/action-plans/${id}/assignees/${uid}`,
      // Member
      myList: '/api/action-plans/me',
    },
  },
  backendPages: {
    payQr: (paymentId: number) => `/pay/qr/${paymentId}`,
    payCash: (paymentId: number) => `/pay/cash/${paymentId}`,
    payCheque: (paymentId: number) => `/pay/cheque/${paymentId}`,
    payReceipt: (paymentId: number) => `/pay/receipt/${paymentId}`,
    receipt: (receiptNo: string) => `/receipt/${receiptNo}`,
    tokenView: (tokenNo: string) => `/token/${tokenNo}`,
    tokenPrint: (tokenNo: string) => `/token/print/${tokenNo}`,
    tokenPrintBulk: (batchId: string) => `/token/print/bulk/${batchId}`,
  },
} as const
